// AUTOGENERATED: DO NOT MODIFY
// edgeql:8C0C1D118ED8DCA142C4EE3EA651624B7724DCE93E948675ACD9CBF5A332FDBB
// Generated on 2022-08-26T13:31:14.0776438Z
#nullable enable
using EdgeDB;

namespace EdgeDB.Generated;

#region Types
[EdgeDBType]
public sealed class UpdateUserResult
{
    [EdgeDBProperty("id")]
    public Guid Id { get; set; }
}

#endregion

public static class UpdateUser
{
    public static readonly string Query = @"UPDATE Person FILTER .id = <uuid>$id SET {
  name := <str>$name,
  email := <str>$email,
}";

    public static Task<IReadOnlyCollection<UpdateUserResult?>> ExecuteAsync(IEdgeDBQueryable client, Guid id, String? name, String? email, CancellationToken token = default)
        => client.QueryAsync<UpdateUserResult>(Query, new Dictionary<string, object?>() { { "id", id }, { "name", name }, { "email", email } }, capabilities: (Capabilities)18446744073709551615ul, token: token);

    public static Task<IReadOnlyCollection<UpdateUserResult?>> UpdateUserAsync(this IEdgeDBQueryable client, Guid id, String? name, String? email, CancellationToken token = default)
        => ExecuteAsync(client, id, name, email, token: token);
}
#nullable restore
