using EdgeDB.QueryNodes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EdgeDB
{
    internal class NodeBuilder
    {
        public StringBuilder Query { get; }
        public List<QueryNode> Nodes { get; }
        public NodeContext Context { get; }
        public Dictionary<string, object?> QueryVariables { get; }
        public List<QueryGlobal> QueryGlobals { get; }
        public bool IsAutoGenerated { get; init; }

        public NodeBuilder(NodeContext context, List<QueryGlobal> globals, List<QueryNode>? nodes = null, Dictionary<string, object?>? variables = null)
        {
            Query = new();
            Nodes = nodes ?? new();
            Context = context;
            QueryGlobals = globals;
            QueryVariables = variables ?? new();
        }
    }
}
