using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EdgeDB.QueryNodes
{
    internal abstract class QueryNode<TContext> : QueryNode
        where TContext : NodeContext
    {
        protected QueryNode(NodeBuilder builder) : base(builder) { }

        protected TContext Context
            => (TContext)Builder.Context;
    }

    internal abstract class QueryNode
    {
        public bool IsAutoGenerated
            => Builder.IsAutoGenerated;
        protected readonly NodeBuilder Builder;
        protected StringBuilder Query
            => Builder.Query;

        public QueryNode(NodeBuilder builder)
        {
            Builder = builder;
        }

        public abstract void Visit();
        public virtual void FinalizeQuery() { }

        protected void SetVariable(string name, object? value)
            => Builder.QueryVariables[name] = value;

        protected void SetGlobal(string name, object? value)
            => Builder.QueryGlobals[name] = value;

        internal BuiltQueryNode Build()
            => new(Query.ToString(), Builder.QueryVariables);
    }

    internal class BuiltQueryNode
    {
        public string Query { get; init; }
        public IDictionary<string, object?> Parameters { get; init; }

        public BuiltQueryNode(string query, IDictionary<string, object?> parameters)
        {
            Query = query;
            Parameters = parameters;
        }
    }
}
